### ISSUE TITLE
Juttle support for Redis

### ISSUE THREAD

**Issue by dmehra** [juttle/redis-adapter#4]
Writeup by @davidvgalbraith:

[Redis](http://redis.io/) is a database-type thing that's pretty popular, so we want Juttle users to be able to write and read from it. Its worldview is pretty different from that of any other backend we've implemented support for so far, so let's see how we can reconcile them into something usable.

## Redis

Redis is a key-value store. So you give it commands like "SET X 1", and then you can do "GET X" and it'll give you 1. Actually, it'll give you "1", because Redis doesn't know about numbers. Values can be strings, lists of strings, HashMap<String, String>s, sets of strings, sorted sets of strings, bitmap strings, and HyperLogLogs, whatever those are. Each one of these value types has a special Redis method for setting and querying values of that type. Here's an example of a hash map:

```
> HMSET x a 1 b 2
OK
> HMGET x a
1) "1"
```

So what I did there was I set the value of the key "x" to be the hash map {a: 1, b: 2}, and then I queried the value of a for the hash map stored at x.

There is an [alphabet soup](http://redis.io/commands) of other commands you can use to analyze Redis data.

### Read

Redis queries return either numbers or arrays of strings. Juttle needs to transform these into Javascript objects for the flowgraph to analyze. There doesn't seem to be much of a way to get any Juttley grammar-type abstraction out of Redis's query language, so let's just have readx redis take a mandatory "-raw" option specifying a Redis query string. We'll execute this query using the rawCallAsync method of a promisified [redis-fast-driver](https://www.npmjs.com/package/redis-fast-driver). Then we'll have to do some post-processing wherein we translate the resulting array of strings into a Javascript object. Let's check out the read-style Redis sources and how we can make sense of their output.

```
BITCOUNT/BITPOS/BRPOPLPUSH/CONFIG GET/DECR/DECRBY/DEL/ECHO/EXISTS/GETBIT/GETSET/GETRANGE/HDEL/HEXISTS/HGET/HINCRBY/HINCRBYFLOAT/HSETNX/HSTRLEN/INCR/INCRBY/INCRBYFLOAT/LASTSAVE/LINDEX/LINSERT/LLEN/LPOP/LPUSH/LPUSHX/LREM/MSETNX/PFADD/PFCOUNT/RANDOMKEY/RENAMENX/RPOP/RPOPLPUSH/RPUSH/RPUSHX/SADD/SCARD/SDIFFSTORE/SETBIT/SETRANGE/SISMEMBER/SMOVE/SREM/STRLEN/ZADD/ZCARD/ZCOUNT/ZINCRBY/ZINTERSTORE/ZLEXCOUNT/ZRANK/ZREM/ZREMRANGEBYLEX/ZREMRANGEBYRANK/ZREMRANGEBYSCORE/ZREVRANK/ZSCORE/ZUNIONSTORE
```

These functions all perform some analysis on the value at a given key or keys and return a single integer or string as their result. Let's emit this result in a one-field object where the field is named "value" and the value is the result.

#### GET

GET takes a key with a string value and returns the value. We can turn it into a point mapping the key to the value.

#### BLPOP/BRPOP

These guys are variadic functions that take as arguments any number of keys whose values are lists, and from the first such list that is nonempty they remove the last element and return a two-element array whose first element is the key that mapped to the nonempty list and whose second element is the value removed from that list. Let's emit this as a point with a key called "list" and a key called "value".

#### CONFIG SET/CONFIG RESETSTAT/LSET/LTRIM/MSET/PFMERGE/RENAME/SELECT/SETEX/

These functions return the string "OK". Let's just swallow that and emit EOF if there was no error.

#### HGETALL

This takes a key whose value is a hash and returns an array where for n = 0,1,2..., the 2n<sup>th</sup> item is the name of a key in the hash and the 2n+1<sup>th</sup> item is the value of that key. We have the technology to rebuild the hash from this and emit that.

#### HKEYS/HVALS

These take a key whose value is a hash and return an array of the keys or of the values in the hash. It seems like the best way to make this into a Juttle object is to map each item in this array to True.

#### KEYS

Like HKEYS, but operates on the global namespace. There is no VALUES for the global namespace.

#### MGET

This takes a list of keys whose values are strings and returns an array containing the values, or null if there is not a string value for a given key. We can map the nth input key to the nth output value to make an object.

#### SDIFF/SINTER/LRANGE/SMEMBERS/SORT/SPOP/SRANDMEMBER/SUNION/ZRANGE/ZRANGEBYLEX/ZREVRANGEBYLEX/ZRANGEBYSCORE

These perform operations on lists or sets and return an array containing the elements of a new list or set. Let's turn this into an array of objects with a key called "value" whose value is the corresponding item in the array.

### Write

There are several ways users might want to write data into Redis. Let's survey them.

#### APPEND

The APPEND command takes a key whose value is a string and another string argument, and it concatenates the argument string to the end of the stored string.

#### SET

As above, SET takes a key and a value string and sets the value as the value of the key.

#### HSET

HSET takes three strings, and it uses the first string as a key whose value is a hash mapping the second to the third.

#### HMSET

HMSET takes an odd number of strings, and it uses the first string as a key whose value is a hash mapping each even-indexed element to the next odd-indexed element, as in the example above.

#### LINSERT

Adds a string to a list at a specified position.

#### LPUSH

Adds a string to the beginning of a list.

#### RPUSH

Adds a string to the end of a list.

#### MSET

Like SET, but takes any number of key-value pairs to set.
 
So there are lots of ways to write, and they all depend on pulling strings off the points to form queries. So let's use string interpolation here. The unfortunate thing is that string interpolation in Juttle is somewhat limited, so we can't pass a string to interpolate as an option to the writex proc. Instead, we have to set it as a field on each point. So here's a command that writes the point `{a: 1, time: "2015-11-25T00:13:08.862Z"}` as a hash which is the value of the key "test":

```
emit -points [{"a":"1","id":"test","time":"2015-11-25T00:13:08.862Z"}] | put redis_write_command = "HMSET ${id} a ${a} time ${time}" | writex redis
```

And then to read the point back you'd do

```
readx redis -raw "HMGET test a time"
```

And here's how one might implement timeseries:

```
emit -limit 100 | put series = 'my_series', value = count(), redis_write_command = "APPEND ${series} '${time} ${value} ' | writex redis
```

and then

```
readx redis -raw "LRANGE my_series 0 100"
```

would give you 100 points like `{value: '2015-11-25T00:46:30.276Z 1'}`, which you could parse into the actual time and value fields. Not ideal, but it's about all I could do with the built-in Redis APIs.

**Comment by henridf** [comment]
I'm not sure if this is part of the plan already but I don't see any mention of live above so here goes...

I'm considering using redis pub/sub in a pretty standard way in my app. With that in place, if I use Juttle, the natural thing I'd want to do is live reads from a redis channel subscription into a long-running juttle process. Similarly a long-running process might want to write into a redis channel subscription.

(And of course likewise for Kafka, Kinesis, ...)

**Comment by davidvgalbraith** [comment]
Great! We will support a live setup like that.

**Comment by dmehra** [comment]
@davidvgalbraith should we move the content of this issue into README.md?

**Comment by davidvgalbraith** [comment]
This issue is very broad. I will close it since https://github.com/juttle/redis-adapter/pull/3 is merged and open issues for making a README and implementing live.
